services:
  web:
    image: ghcr.io/malothecat/leon_wishlist:latest
    container_name: leon_wishlist_web
    restart: unless-stopped
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${LEON_WISHLIST_DATABASE_PASSWORD}@192.168.1.128:5432/leon_wishlist_production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "80:3000"
    depends_on:
      - redis
    volumes:
      - storage_data:/rails/storage
      - log_data:/rails/log
    networks:
      - leon_wishlist_network

  redis:
    image: redis:7-alpine
    container_name: leon_wishlist_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - leon_wishlist_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
  storage_data:
    driver: local
  log_data:
    driver: local

networks:
  leon_wishlist_network:
    driver: bridge
