default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: leon_wishlist_development

test:
  <<: *default
  database: leon_wishlist_test

production:
  <<: *default
  host: 192.168.1.128  # IP du container PostgreSQL
  port: 5432
  database: leon_wishlist_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["LEON_WISHLIST_DATABASE_PASSWORD"] %>